name: Test CI

on:
  # Triggers the workflow on push and pull request events but only for pull_requests on the main branch
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:      
    - name: Checkout repository and submodules
      uses: actions/checkout@v3

    - name: Prepare 
      run: |
        # Rename example .env file
        mv .env.example .env

        # Set environment variables from .env file
        export $(cat .env | xargs) 
        
        # Generate ssh keys
        mkdir -p ./ssh
	      ssh-keygen -t rsa -q -f $MANAGER_KEY -P '' -C 'OCR-D manager key'

    - name: Docker Compose build
      run: docker compose build

    - name: Test
      run: make test 
